### PR TITLE
Allow specifying I2C address

### PR DESCRIPTION
**Pull request by nnarain**

### CODE REVIEW

**Comment by justacec** [comment]
@ryanrightmer  I was going to go ahead and merge this into master and then close the other PR unless you had any reservations.  Did not get any feedback on the other PR yet.  Thoughts?

**Comment by nnarain** [comment]
I don't think I realized at the time I made this MR there was another one addressing the same thing. That said, I do think limiting the options to the two in the datasheet make a bit more sense. Either way it will allow a user to specify the address they need.

**Comment by justacec** [comment]
Ok, I am going to go ahead and close the PR in favor of the alternate approach.  Thanks for taking the time to put the PR together.

**Comment by justacec** [comment]
Opps, I got this backwards (sigh).  I will merge this one in vice the other approach.

**Pull request merged**
